[ Featuer ] Home/MovieService
yjjem/MoviePedia pull request #4
Opened 2023-04-12 10:18 UTC by yjjem

### PR 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
**`feat/home/movie-service`** -> **`develop`**

### 변경 사항
1.  MovieServiceInterface 추가
2.    MovieService 구현 ( manager를 통해 받은 data를 parsing해주는 역할 )
      | name 	| feature 	| return 	|
      |------	|---------	|--------	|
      |    카테고리별 영화 리스트  	|   loadMovieList      	|       GenericResponse<[Movie]> 	|    
      |    영화 리뷰 리스트 	|         loadReviewList	|       GenericResponse<[Response]> 	|      	
      |    영화 비디오 리스트  	|       loadVideoList  	|        GenericResponse<[Video]>	|      	
      |    영화 키워드 리스트 	|       loadKeywordList  	|        GenericResponse<[Keyword]>	|      	
      |    영화 제공자 리스트 	|       loadProviderList  	|        GenericResponse\<ProvidersByCountryResponse>	| 
      |    비슷한 영화 리스트 	|       loadSimilarMovieList  	|       GenericResponse<[Movie]> 	|   
 
4.  MovieService 테스트 추가
    - `test_loadMovieList실행_decoding실패시_오류_반환하는지`
    - `test_loadMovieList실행_networkManager_에러가_올바르게_들어오는지`
    - `test_loadMovieList_문제없을시_정상적으로_MovieList를_반환하는지`
    - `test_loadReviewList_문제없을시_정상적으로_ReviewList를_반환하는지`
    - `test_loadVideoList_문제없을시_정상적으로_VideoList를_반환하는지`
    - `test_loadKeywordList_문제없을시_정상적으로_KeywordList를_반환하는지`
    - `test_loadProviderList_문제없을시_정상적으로_ProviderList를_반환하는지`
    - `test_loadSimilarMovieList_문제없으시_정상적으로_MovieList를_반환하는지`
5. Path 생성시 `/`  를 붙여주지 않아 발생한 문제 fix
6. EndPoint 타입 추가
    ```swift 
    struct EndPoint {
        let host: String
        let path: String
        let queryItems: [QueryKey: String]?
        
        var url: URL? {
            var components = URLComponents(string: host)
            components?.path = path
            components?.queryItems = queryItems?.map { URLQueryItem(name: $0.name, value: $1) }
            return components?.url
        }
    }
    ```
7. Bundle을 통한 apikey 로드 기능 추가
8.  비슷한 형태의 Response를 하나의 GenericResponse<Item: Decodable> 로 통일하여 불필요한 반복 객체들을 줄였습니다.
    ```swift
    // Before

    struct Response1: Decodable{
       let id: Int
       let results: [ ... ]
    }
    
    struct Response2: Decodable{
       let id: Int
       let results: ...
    }
    
    // After
    
    struct GenericResponse<Item: Decodable> {
       let id: Int
       let results: Item
       let keywords: Item
       ...
    }
    ```
### 테스트 결과
<img width="680" alt="스크린샷 2023-04-12 18 17 52" src="https://user-images.githubusercontent.com/88357373/231412953-8dd323f9-124b-41f0-b642-98341d4131d5.png">

### 궁금한 점 

현재 MovieService는 EndPoint를 만들어 networkManager에게 전달하며 받아온 Response Data를 디코딩하는 역할을 수행합니다.
객체가 2가지 역할을 수행하고있다고 볼 수 있을 것 같은데. 혹시 문제가 있는 구현일까요 ??

/br

2023-04-12 16:17 UTC, 1Consumption requested changes

2023-04-12 16:17 UTC, 1Consumption commented on remy-movie/Test/Helpers/Print Helper.swift
> +}
꼭 필요한 메소드일까요🤔

2023-04-12 16:17 UTC, 1Consumption commented on remy-movie/Test/ServicesTest/MovieServiceTest.swift
> +    var sut: MovieService?
private을 붙여주세요.

2023-04-12 16:17 UTC, 1Consumption commented on remy-movie/Test/ServicesTest/MovieServiceTest.swift
> +        }
`MovieService`는 `Networkable` 프로토콜을 채택한 객체에게 이벤트를 보냅니다. 그렇다면 `Networkable`를 채택한 Mock객체를 통해 행위 검증을 하는게 올바른 테스트 아닐까요?
한뎊스 더 들어간 `MockURLProtocol`은 테스트에 불필요해보입니다.

2023-04-12 16:17 UTC, 1Consumption commented on remy-movie/remy-movie/Data/Service/Movie/GenericResponse.swift
> +}
https://developer.apple.com/videos/play/wwdc2022/110352/
이 영상에 나오는 내용을 토대로 리팩토링 해볼 수 있을까요?

2023-04-12 16:17 UTC, 1Consumption commented on remy-movie/remy-movie/Data/Service/Movie/MovieService.swift
> +    }
정말 많~은 역할을 하네요. 정말 이 객체에서 다 해야하는 일인가요?

2023-04-18 05:54 UTC, yjjem commented on remy-movie/remy-movie/Data/Service/Movie/MovieService.swift
> +    }
여러 영화 정보를 보여줄 `Home Scene`에서 사용할 목적으로 만든 서비스 객체입니다. 
다시 생각해보면 `loadMovieList`를  제외한 나머지 메소드들은 **특정 영화**의 **부가적인 정보**들을 받아오기 위한 메소드들이기 때문에 분리해주는 것이 좋을 것 같습니다.

2023-04-18 05:58 UTC, yjjem commented on remy-movie/Test/Helpers/Print Helper.swift
> +}
굳이 필요하지 않은 메소드를 정의한 것 같습니다. 필요하다면 아래의 메소드들을 활용하면 될 것 같습니다.
`printErrorWithDetailsOfFunction`은 삭제했습니다 !

<img width="748" alt="스크린샷 2023-04-18 11 47 33" src="https://user-images.githubusercontent.com/88357373/232657617-6bc13af8-2c31-4ed1-89e5-e4f7b0c7da6b.png">

2023-04-18 05:58 UTC, yjjem commented on remy-movie/Test/ServicesTest/MovieServiceTest.swift
> +    var sut: MovieService?
private 지정했습니다 👍

2023-04-18 06:10 UTC, yjjem commented on remy-movie/remy-movie/Data/Service/Movie/GenericResponse.swift
> +}
좋은 영상 감사합니다. 

Generic을 활용한 다형성 확보와 보일러플레이트 코드를 줄이는 방법에 대한 영상인 것 같습니다.
 
위 객체와 관련된 것은 **서브 타입 다형성**인 것으로 보이는데 Interface를 분리하고 Respose 별로 Item의 type을 지정해주는 것이 의도하신 리팩토링 방향과 일치하는지 궁금합니다 !

2023-04-18 08:34 UTC, yjjem commented on remy-movie/Test/ServicesTest/MovieServiceTest.swift
> +        }
다시 생각해보니 말씀해주신 대로 MockURLProtocol을 사용하여 테스트하는 것은 올바르지 않습니다. 
Networkable을 채택한 MockNetworkManager를 구현하여 해당 객체를 통해 테스트하도록 수정하였습니다 👍

```swift

// MovieServiceTest

final class MovieServiceTest: XCTestCase {
    
    private var sut: MovieService?
    
    override func setUpWithError() throws {
        try super.setUpWithError()
        
        let manager = MockNetworkManager()
        sut = MovieService(manger: manager)
    }
```

```swift
// Helpers/MockNetworkManager

final class MockNetworkManager: Networkable {
    
    static var mockHandler: (() -> (NetworkError?, Data?))?
    
    func load(
        url: URL?,
        method: HTTPMethod,
        completion: @escaping (FailableData) -> Void
    ) -> URLSessionDataTask? {
        
        guard let mockHandler = MockNetworkManager.mockHandler else { return nil }
        
        let (error, data) = mockHandler()
        
        if let error = error {
            completion(.failure(error))
        }
        
        if let data = data {
            completion(.success(data))
        }
        
        return nil
    }
    ...
}
```

2023-04-20 13:21 UTC, 1Consumption commented on remy-movie/remy-movie/Data/Service/Movie/GenericResponse.swift
> +}
<img width="651" alt="image" src="https://user-images.githubusercontent.com/37682858/233379195-1439134e-4233-4985-b215-169f986890b7.png">
이 부분을 리팩토링 할 수 있는지를 물어본거였습니다.

2023-04-20 13:21 UTC, 1Consumption commented on remy-movie/Test/ServicesTest/MovieServiceTest.swift
> +        }
https://academy.realm.io/kr/posts/making-mock-objects-more-useful-try-swift-2017/
이 아티클을 참고하면 더 좋겠습니다.

2023-04-20 13:22 UTC, 1Consumption requested changes
고생하셨습니다.

2023-04-20 13:22 UTC, 1Consumption approved these changes
고생하셨습니다.

2023-04-20 14:07 UTC, merged